From: Stephen Blott <smblott+github@gmail.com>
Date: Fri, 14 Feb 2014 16:13:58 +0000
Subject: Fix broken reference to authfile.

---
 cloudprint/cloudprint.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/cloudprint/cloudprint.py b/cloudprint/cloudprint.py
index 376ae5c..da840c1 100755
--- a/cloudprint/cloudprint.py
+++ b/cloudprint/cloudprint.py
@@ -466,7 +466,7 @@ def main():
 
     # Check if password authentification is needed
     if not cpp.get_saved_auth():
-        if authfile is None or not os.path.exists(authfile):
+        if args.authfile is None or not os.path.exists(args.authfile):
           cpp.username = raw_input('Google username: ')
           cpp.password = getpass.getpass()
 
